### ISSUE TITLE
OwnerReference on applied resources

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#65] opened 2024-01-29 04:39 UTC
We should have an OwnerReference (to the GitSync) on any resources we apply, so that if the GitSync were deleted, then all of the resources would automatically be deleted as well.

**Comment by xdevxy** [comment] 2024-03-18 18:28
As cross-namespace owner references are disallowed by design, we will not proceed this. Closed this issue for now.

**Closed by xdevxy** 2024-03-18 18:28 UTC
